-- @block CREATE DATABASE
CREATE DATABASE IF NOT EXISTS incvo;
CREATE SCHEMA IF NOT EXISTS incvo;


-- @block VIEW ALL DATABASE
SHOW DATABASES;


-- @block SHOW CREATED DATABASE
SHOW CREATE DATABASE incvo;


-- @block DELETE DATABASE
DROP SCHEMA IF EXISTS incvo;
DROP DATABASE IF EXISTS incvo;


-- @block USE PARTICULAR DATABASE
USE incvo;


-- @block VIEW ALL CHARSET
SHOW CHARACTER SET;


-- @block view all tables
SHOW TABLES;
